version: '3'
services:
  nginx:
    build: ./web
    ports:
      - "80:80"
    depends_on:
      - flask_app

  flask_app:
    build: ./app
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgres://postgres:password@db:5432/mydatabase"
      CACHE_URL: "redis://cache:6379/0"
    depends_on:
      - db
      - cache

  db:
    build: ./db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data

  cache:
    build: ./cache
    volumes:
      - cache_data:/data

volumes:
  db_data:
  cache_data:
